name: Deploy API Users

on:
  push:
    branches: [main]

jobs:
  deploy:
    uses: 1c2025-IngSoftware2-g7/ci_templates/.github/workflows/deploy-render.yml@5d62513
    with:
      render-webhook-url: ${{ secrets.RENDER_HOOK }}
    secrets:
      FLASK_APP: src.app:users_app
