name: Deploy Users Service on GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: ./.github/workflows/deploy-gke.yml
    with:
      service-name: api-users
      docker-context: .
      docker-tag: v1
      k8s-path: k8s
